version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      - "4201:4200"
    working_dir: /app
    volumes:
      - ./src/app:/app/src/app:cached # <--- This will map . to /root inside the container.